<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Recursos\icono_goikoa.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>AnyCPU</PlatformTarget>
	<Version>1.0.3.0</Version>
	<AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Recursos\CamaraIcon.png" />
    <None Remove="Recursos\CamaraMenuIcon.png" />
    <None Remove="Recursos\CloseIcon.png" />
    <None Remove="Recursos\ErrorIcon.png" />
    <None Remove="Recursos\GamFamilyIcon.png" />
    <None Remove="Recursos\GoikoaHomeImage.png" />
    <None Remove="Recursos\GoikoaIcon.png" />
    <None Remove="Recursos\HomeIcon.png" />
    <None Remove="Recursos\InformationIcon.png" />
    <None Remove="Recursos\ListadoOrdenesIcon.png" />
    <None Remove="Recursos\QuestionIcon.png" />
    <None Remove="Recursos\updatedIcon.png" />
    <None Remove="Recursos\WarningIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Recursos\CamaraIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\CamaraMenuIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\CloseIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\ErrorIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Content Include="Recursos\icono_goikoa.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Recursos\GoikoaHomeImage.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\GoikoaIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\HomeIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\GamFamilyIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\InformationIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes.Wpf" Version="1.0.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Recursos\ListadoOrdenesIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\QuestionIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\updatedIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\WarningIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="CertificatesAuth\envdev-auth.goikoa.com.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="CertificatesAuth\envpre-auth.goikoa.com.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="CertificatesAuth\envpro-auth.goikoa.com.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="CertificatesAuth\InstallCertificate.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\envdev.goikoa.com.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\envpre.goikoa.com.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\envpro.goikoa.com.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\InstallCertificate.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Prerequisites\dotnet-runtime-8.0.14-win-x64.exe">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Prerequisites\windowsdesktop-runtime-8.0.14-win-x64.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\icono_goikoa.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\icono_goikoaPNG.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="VersionApp\manifest.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CertificatesAuth\" />
  </ItemGroup>
</Project>
